sonar.projectKey=nsasika_ns-acdmy-fe
sonar.organization=nsasika
sonar.projectName=Nalin's Academy

sonar.sources=src,scripts
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/public/**,next-env.d.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
