import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import theme from "../theme";
import "./globals.css";
import Sidebar from "@/components/Sidebar"; // Extracted Sidebar to its own component
import { roboto, geistSans, geistMono } from "@/styles/fonts"; // Import fonts

export const metadata: Metadata = {
  title: "Nalin's Academy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <div className="flex min-h-screen">
              <Sidebar />
              <main className="flex-1 p-8 bg-gray-100">{children}</main>
            </div>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}